# Generated by Django 5.1.2 on 2024-10-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalcars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
