# Generated by Django 5.1.2 on 2024-11-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalcars', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='license_number',
            new_name='driving_license',
        ),
    ]
